### ISSUE TITLE
when trying 03_RAG/rag.py ， there is an Error

### ISSUE THREAD

**Issue by zgimszhd61** [lamini-ai/lamini-examples#33]
Traceback (most recent call last):
  File "/Users/a0000/mywork/commonLLM/opensource/lamini-sdk/03_RAG/rag.py", line 13, in <module>
    runner.index.save_index("index")
  File "/Users/a0000/mywork/commonLLM/opensource/lamini-sdk/03_RAG/lamini_index.py", line 86, in save_index
    logger.debug("Index size: %d", self.index.ntotal)
                                   ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ntotal'

**Comment by yx-lamini** [comment]
Rag tuning is moved, sorry for the inconvenience.
You should run the python code with the provided script. It sets up the docker environment.
Directly running python code does not work.

![image](https://github.com/user-attachments/assets/adaa57cd-ef0d-419e-bfc2-035d248b3eb5)
