### ISSUE TITLE
UnicodeDecodeError from DirectoryLoader function

### ISSUE THREAD

**Issue by amd-maheshs3** [lamini-ai/lamini-examples#63]
what files can be loaded using DirectoryLoader class?

```py
Traceback (most recent call last):
  File "/app/mahesh/lamini/lamini-sdk/test.py", line 17, in <module>
    for chunk in tqdm(loader):
  File "/app/miniconda3/envs/mahesh/lib/python3.11/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/app/mahesh/lamini/lamini-sdk/RAG_03/directory_loader.py", line 51, in get_chunk_batches
    for chunk in self.get_chunks():
  File "/app/mahesh/lamini/lamini-sdk/RAG_03/directory_loader.py", line 15, in get_chunks
    for text in data:
  File "/app/mahesh/lamini/lamini-sdk/RAG_03/directory_loader.py", line 41, in load
    yield f.read()
          ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 6: invalid start byte


```

**Comment by yx-lamini** [comment]
Do you have a more complete example, so that we might be able to reproduce your issue?
